<div class="dashboard">
    <div class="page-title">
        <h1><?=$this->__('My Dashboard') ?></h1>
    </div>
	<?=$this->getMessagesBlock()->getGroupedHtml() ?>
	<?=$this->getChildHtml('hello') ?>
	<?php
		$customer               = $this->getCustomer();
		$customerGroup          = $customer->getGroupId();
		$SelectedCustomerGroups =   Mage::getStoreConfig('payment/iri/specificcustomers'); 
		$SelectedCustomerGroupsArray = explode(",", $SelectedCustomerGroups);
	?>
	<?php  if(in_array($customerGroup, $SelectedCustomerGroupsArray)) :?>
		<?=$this->getChildHtml('credit'); ?>
	<?php endif;?>
      
    <?=$this->getChildHtml('top') ?>
    <div class="box-account box-info">
        <div class="box-head">
            <h2><?=$this->__('Account Information') ?></h2>
        </div>
        <?php /* Extensions placeholder */ ?>
        <?=$this->getChildHtml('customer.account.dashboard.extra') ?>
        <?=$this->getChildHtml('info') ?>
       
        <?=$this->getChildHtml('address') ?>
    </div>
    <?=$this->getChildHtml('info1') ?>
    <?=$this->getChildHtml('info2') ?>
</div>


