   <div class="box-account">
                    <div class="box-head">
                        <h2><?php echo $this->__('Credit Limit')?></h2>
                    </div>
                     <div>
                               <?php  
                                   $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
                                   $CrditBalance = $currencySymbol.$this->getCustomer()->getCreditLimit();?>                                   <?php echo $this->__('Your Credit balance is ').$CrditBalance;?>
                               
                         </div>
                    
            </div>
           
